<a href="https://colab.research.google.com/github/ImMatt-blip/ba-ai-project/blob/main/week2_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd, sqlite3

df = pd.read_csv("/content/AI_SocialMedia_Student_Dataset[1].csv")

df = df.drop_duplicates().dropna()

df.columns = (df.columns.str.strip()
    .str.lower().str.replace(" ", "_"))

In [13]:
df.head()

,student_id,age,gender,education_level,daily_social_media_hours,daily_ai_tool_usage_hours,sleep_hours,physical_activity_hours,mental_health_score,physical_health_score
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04

In [14]:
conn = sqlite3.connect(":memory:")
df.to_sql("data", conn, index=False)

def q(sql):
    return pd.read_sql(sql, conn)

In [15]:
q("SELECT * FROM data LIMIT 5")

,student_id,age,gender,education_level,daily_social_media_hours,daily_ai_tool_usage_hours,sleep_hours,physical_activity_hours,mental_health_score,physical_health_score
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04

In [16]:
q("SELECT COUNT(*) FROM data")

   COUNT(*)
0     16000

In [17]:
df.dtypes

student_id                    object
age                            int64
gender                        object
education_level               object
daily_social_media_hours     float64
daily_ai_tool_usage_hours    float64
sleep_hours                  float64
physical_activity_hours      float64
mental_health_score          float64
physical_health_score        float64
dtype: object

My table has 16,000 rows.

One row = one student.

Numbers to analyze: age, daily_social_media_hours, daily_ai_tool_usage_hours, sleep_hours, physical_activity_hours, mental_health_score, physical_health_score.

Groups to compare: education_level and gender.

In [18]:
q("""
SELECT COUNT(*) AS students_above_75
FROM data
WHERE mental_health_score > 75
""")

   students_above_75
0               7104

Finding: 7,104 students had a mental health score above 75.

In [19]:
q("""
SELECT education_level,
    SUM(mental_health_score) AS total_mental_health_score
FROM data
GROUP BY education_level
ORDER BY total_mental_health_score DESC
""")

  education_level  total_mental_health_score
0     High School                  440071.90
1      University                  364427.32
2         College                  355391.87

Finding: High School students had the highest total mental health score at 440,071.90.

In [20]:
q("""
SELECT age,
    AVG(mental_health_score) AS avg_mental_health_score
FROM data
WHERE education_level = 'University'
GROUP BY age
ORDER BY avg_mental_health_score DESC
LIMIT 5
""")

   age  avg_mental_health_score
0   22                72.875154
1   23                72.415026
2   24                72.412320
3   25                72.265000

Finding: Among University students, age 22 had the highest average mental health score at 72.88.